name: Build Linux RPM App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # سيرفور أوبونتو لبناء الحزمة

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Install RPM Build Tools
        run: sudo apt-get update && sudo apt-get install -y rpm

      - name: Build RPM App
        run: npx electron-builder --linux rpm

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: floatboard-fedora-rpm
          path: dist/**/*.rpm
